version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: strongpassword
      MARIADB_DATABASE: mydatabase
      MARIADB_USER: admin
      MARIADB_PASSWORD: strongpassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
