version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: strongpassword
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    mongo:
        image: mongo:latest
        container_name: mongo_db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: strongpassword
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    redis:
        image: redis:latest
        container_name: redis_db
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
    mongo_data:
    redis_data:
